# Generated by Django 3.2.4 on 2021-06-14 16:10

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(template='blocks/heading_block.html')), ('image', wagtail.images.blocks.ImageChooserBlock(template='blocks/image_block.html')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('carousel', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.RichTextBlock())]))], null=True),
        ),
    ]
