# Generated by Django 3.2.4 on 2021-06-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_socialmediasettings_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='facebook',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='pinterest',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='twitter',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='youtube',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
