# Generated by Django 3.2.4 on 2021-06-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_auto_20210615_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='github',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
